[simulation]
N = 600
dz = 1e-2
dt = 1e-11
steps = 2000

[boundary]
left = PEC
right = PEC

[material.vacuum]
eps_r = 1
mu_r = 1

[region]
start = 0
end = 600
material = vacuum

[source]
position = 300
type = Ey
file = sources/sin.c
function = pulse

[analyzer]
file = analyzers/plot.c
init = init
process = process
finish = finish
