[simulation]
N = 600
dz = 1e-2
dt = 1e-11
steps = 5000

[boundary]
left = PEC
right = PEC

[material.vacuum]
eps_r = 1
mu_r = 1

[material.a]
eps_r = 3.2
mu_r = 1

[region]
start = 0
end = 500
material = vacuum

[region]
start = 500
end = 600
material = a

[source]
position = 300
type = Ey
file = sources/sin.c
function = pulse
